const functions = require("firebase-functions")
const express = require('express')
const app = express()
const {getSingleCars,getCars,newCars,newMultiCars,updateCars,deleteCars} = require('./src/cars')
app.get('/cars/all',getCars)
app.get('/cars',getSingleCars)
app.post('/cars',newCars)
app.post('/cars/multiple',newMultiCars)
app.patch('/cars/:carId',updateCars)
app.delete('/cars/:carId',deleteCars)
exports.app = functions.https.onRequest(app)

